### ISSUE TITLE
Cannot download any file other than of an image type

### ISSUE THREAD

**Issue by es-ihar** [haiwen/seadroid#1040]
Not sure when this issue appeared, most likely since the latest Samsung FW update (2 weeks ago). 
Now Seadroid (v3.0.6) cannot download any file anymore, with the only exception of image files. The directory structure is visible ok, 
When I try to download a file, it fails with "Failed to download file 'Network error'" (see screenshot below)
I tried re-installing the app, downgrading (tried down to 3.0.3), nothing of those helps.
Also, when selecting a file by long-press, I cannot select anything from the menu (options are all greyed-out), so I cannot do any other operation on a file anyway.
Phone is Samsung S23+ with Android 14 / OneUI 6.1
The other clients I use (on Windows) work ok with the same server/account/libraries.
EDIT: If I downgrade Seadroid to v2.3.7, everything works fine.

<img src="https://github.com/user-attachments/assets/97374ee7-60cf-4f67-a682-4b789c0b34cc" alt="Screenshot_20241210_154003_Seafile" width="300">

**Comment by mg2k** [comment]
I'm having the same problem since a few months, always need to go back to v2, since it's working there.
I'm on a Samsung A51 5G, last FW update was in June 2024.

**Comment by 300481** [comment]
Same here since Seadroid Update to 3.0.6

* Seadroid 3.0.6

* Seafile 11.0.12 CE as docker container (https://hub.docker.com/layers/seafileltd/seafile-mc/11.0.12/images/sha256-31bdc49cf9a2ec558550aef32ba66616d495790451f5de41e7d4f4740c9b73d1?context=explore)

* Android 14

* Samsung A33 5G

Getting the following error in seahub.log:

`2024-12-11 09:46:40,467 [ERROR] django.request:241 log_response Internal Server Error: /api2/repos/*MASKED_UUID*/file/detail/
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.10/dist-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.10/dist-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.10/dist-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'base_filecomment.uuid_id' in 'WHERE'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-11.0.12/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/seafile/seafile-server-11.0.12/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-11.0.12/seahub/seahub/api2/views.py", line 3314, in get
    comment_total = file_comments.count()
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/seafile/seafile-server-11.0.12/seahub/thirdpart/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.10/dist-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.10/dist-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.10/dist-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'base_filecomment.uuid_id' in 'WHERE'")`

**Comment by ivohar** [comment]
My seahub.log when the error occurs is similar to the one of @300481 :

2024-12-11 21:00:26,996 [ERROR] django.request:132 handle_uncaught_exception Internal Server Error: /owncloud/api2/repos/792c191e-5176-4917-af56-c6a9f726b45b/file/detail/
Traceback (most recent call last):
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: base_filecomment.uuid_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/seahub/api2/views.py", line 3206, in get
    comment_total = file_comments.count()
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/db/models/query.py", line 364, in count
    return self.query.get_count(using=self.db)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/db/models/sql/query.py", line 499, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/db/models/sql/query.py", line 480, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/seafile/owncloud/seafile-server-7.1.5/seahub/thirdpart/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: base_filecomment.uuid_id
2024-12-11 21:00:27,468 [WARNING] django.request:150 get_response Not Found: /owncloud/api/v2.1/repos/792c191e-5176-4917-af56-c6a9f726b45b/custom-share-permissions/

**Comment by arcepi** [comment]
I've been checking all the SQL "upgrade" scripts in the seahub folder and it seems that adding uuid_id column to table base_filecomment is never done.

However, the column is in the database definition for a clean install.

**Comment by 300481** [comment]
@arcepi  awesome!

**Comment by freeplant** [comment]
I think fixing the missing base_filecomment.uuid_id should solve the issue.

For the correct version of MySQL tables, please refer to the following links:

seahub_db: https://github.com/haiwen/seahub/blob/master/sql/mysql.sql
seafile_db and ccnet_db: https://github.com/haiwen/seafile-server/tree/master/scripts/sql/mysql

**Comment by ivohar** [comment]
This sounds good, but can you provide some instructions on how to do that?

**Comment by arcepi** [comment]
I fixed the problem in my instance.

Execute the following statements in your seahub database:

```
alter table `base_filecomment` add column `uuid_id` char(32) NOT null;
alter table `base_filecomment` add KEY `base_filecomment_uuid_id_4f9a2ca2_fk_tags_fileuuidmap_uuid` (`uuid_id`);
alter table `base_filecomment` add CONSTRAINT `base_filecomment_uuid_id_4f9a2ca2_fk_tags_fileuuidmap_uuid` FOREIGN KEY (`uuid_id`) REFERENCES `tags_fileuuidmap` (`uuid`);
```

Personally I used DBeaver. But you can run it using mysql cli command.

**Comment by ivohar** [comment]
Great, thanks!

**Comment by ivohar** [comment]
Below is how I fixed the problem in my instance. I could not use the procedure @arcepi followed, because I am running SQLite databases, not MySQL ones. I prefer to keep it that way, because MySQL is heavy and optimized for large concurrent access, while I am running Seafile on a relatively weak machine , for a small group of users. 
After the procedure I also upgraded Seafile server from 7.1.5 to 9.0.10, which fixed some other issues with latest Seadroid as well (like selecting a file by long-press not doing anything).

In SQLite alter table statements are not applicable here (tried it - didn't work), since apparently SQLite is limited regarding changes you can apply to an existing table. The workaround is to create a new table, and copy contents from the old table.
Here is the procedure:
- create a backup copy of seahub.db and open the original with sqlite3
- show old table properties
```
sqlite> .schema base_filecomment
CREATE TABLE IF NOT EXISTS "base_filecomment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "repo_id" varchar(36) NOT NULL, "parent_path" text NOT NULL, "repo_id_parent_path_md5" varchar(100) NOT NULL, "item_name" text NOT NULL, "author" varchar(255) NOT NULL, "comment" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "detail" text DEFAULT NULL, "resolved" bool NOT NULL DEFAULT 0);
CREATE INDEX "base_filecomment_02bd92fa" ON "base_filecomment" ("author");
CREATE INDEX "base_filecomment_9a8c79bf" ON "base_filecomment" ("repo_id");
CREATE INDEX "base_filecomment_c5bf47d4" ON "base_filecomment" ("repo_id_parent_path_md5");
CREATE INDEX "base_filecomment_resolved_e0717eca" ON "base_filecomment" 
```
- create new table with another name and the new column added
```
sqlite> CREATE TABLE IF NOT EXISTS "base_filecomment_new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "repo_id" varchar(36) NOT NULL, "parent_path" text NOT NULL, "repo_id_parent_path_md5" varchar(100) NOT NULL, "item_name" text NOT NULL, "author" varchar(255) NOT NULL, "comment" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, `uuid_id` char(32) NOT NULL,  "detail" text DEFAULT NULL, "resolved" bool NOT NULL DEFAULT 0);
```
- copy data from original table into the new table
```
sqlite> INSERT INTO base_filecomment_new(id,repo_id,parent_path,repo_id_parent_path_md5,item_name,author,comment,created_at,updated_at,detail,resolved) SELECT * FROM base_filecomment;
```
- delete old table
```
sqlite> drop table base_filecomment;
```
- rename the new table
```
sqlite> alter table base_filecomment_new rename to base_filecomment;
```
- re-create indexes
```
sqlite> CREATE INDEX "base_filecomment_02bd92fa" ON "base_filecomment" ("author");
sqlite> CREATE INDEX "base_filecomment_9a8c79bf" ON "base_filecomment" ("repo_id");
sqlite> CREATE INDEX "base_filecomment_c5bf47d4" ON "base_filecomment" ("repo_id_parent_path_md5");
sqlite> CREATE INDEX "base_filecomment_resolved_e0717eca" ON "base_filecomment" ("resolved");
sqlite> create index "base_filecomment_uuid_id_4f9a2ca2_fk_tags_fileuuidmap_uuid" ON "base_filecomment" ("uuid_id");
```
- we are done
```
sqlite> .exit
```
