### ISSUE TITLE
Current master crashes on startup if server unreachable

### ISSUE THREAD

**Issue by forouher** [haiwen/seadroid#309]
Steps to reproduce:
1. shutdown your server or make sure its unreachable (do not go into flight mode!)
2. open Seafile app (current master)
3. observe as Seafile closes immediately

It seems to be an uncatched exception originating here:

https://github.com/haiwen/seadroid/blob/master/src/com/seafile/seadroid2/ui/activity/BrowserActivity.java#L336

**Comment by Logan676** [comment]
I have reproduced the error,
```
Caused by: com.github.kevinsawicki.http.HttpRequest$HttpRequestException: java.net.ConnectException: failed to connect to /192.168.1.149 (port 8000) after 15000ms: isConnected failed: ECONNREFUSED (Connection refused)
E/AndroidRuntime( 9120): 	at com.github.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1522)
E/AndroidRuntime( 9120): 	at com.seafile.seadroid2.SeafConnection.checkRequestResponseStatus(SeafConnection.java:1038)
E/AndroidRuntime( 9120): 	at com.seafile.seadroid2.SeafConnection.getServerInfo(SeafConnection.java:209)
E/AndroidRuntime( 9120): 	at com.seafile.seadroid2.data.DataManager.getServerInfo(DataManager.java:152)
E/AndroidRuntime( 9120): 	at com.seafile.seadroid2.ui.activity.BrowserActivity$FetchServerInfoTask.doInBackground(BrowserActivity.java:336)
E/AndroidRuntime( 9120): 	at com.seafile.seadroid2.ui.activity.BrowserActivity$FetchServerInfoTask.doInBackground(BrowserActivity.java:331)
E/AndroidRuntime( 9120): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime( 9120): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 9120): 	... 3 more
E/AndroidRuntime( 9120): Caused by: java.net.ConnectException: failed to connect to /192.168.1.149 (port 8000) after 15000ms: isConnected failed: ECONNREFUSED (Connection refused)
E/AndroidRuntime( 9120): 	at libcore.io.IoBridge.isConnected(IoBridge.java:223)
E/AndroidRuntime( 9120): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
E/AndroidRuntime( 9120): 	at libcore.io.IoBridge.connect(IoBridge.java:112)
E/AndroidRuntime( 9120): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
E/AndroidRuntime( 9120): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
E/AndroidRuntime( 9120): 	at java.net.Socket.connect(Socket.java:843)
E/AndroidRuntime( 9120): 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:131)
E/AndroidRuntime( 9120): 	at com.android.okhttp.Connection.connect(Connection.java:101)
E/AndroidRuntime( 9120): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
E/AndroidRuntime( 9120): 	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
E/AndroidRuntime( 9120): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
E/AndroidRuntime( 9120): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
E/AndroidRuntime( 9120): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
E/AndroidRuntime( 9120): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
E/AndroidRuntime( 9120): 	at com.github.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1520)
E/AndroidRuntime( 9120): 	... 10 more
E/AndroidRuntime( 9120): Caused by: libcore.io.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
E/AndroidRuntime( 9120): 	at libcore.io.IoBridge.isConnected(IoBridge.java:208)
E/AndroidRuntime( 9120): 	... 24 more
E/android.os.Debug( 4564): !@Dumpstate > sdumpstate -k -t -z -d -o /data/log/dumpstate_app_error
```
