### ISSUE TITLE
NPE when opening image

### ISSUE THREAD

**Issue by forouher** [haiwen/seadroid#372]
Reproduced with current master.

steps to reproduce:
1. go to directory with images.
2. tap on an image file
3. BOOM

Backtrace:
```
06-21 12:00:01.553  17115-17115/com.seafile.seadroid2 I/Timeline﹕ Timeline: Activity_launch_request id:com.seafile.seadroid2 time:84884168
06-21 12:00:01.579  17115-17115/com.seafile.seadroid2 D/BrowserActivity﹕ onPause
06-21 12:00:01.579  17115-17115/com.seafile.seadroid2 D/DefaultAppLock﹕ onActivityPaused
06-21 12:00:01.623  17115-17115/com.seafile.seadroid2 D/Account﹕ https://XXXXX/ dariush@XXXXX null 1111111111111111111111111111111111111111
06-21 12:00:01.626  17115-17115/com.seafile.seadroid2 D/DefaultAppLock﹕ onActivityResumed
06-21 12:00:01.696  17115-17115/com.seafile.seadroid2 D/AndroidRuntime﹕ Shutting down VM
06-21 12:00:01.698  17115-17115/com.seafile.seadroid2 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.seafile.seadroid2, PID: 17115
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.seafile.seadroid2.ui.adapter.GalleryAdapter.getItem(int)' on a null object reference
            at com.seafile.seadroid2.ui.activity.GalleryActivity$2.onPageScrolled(GalleryActivity.java:114)
            at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1712)
            at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1633)
            at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:581)
            at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1600)
            at android.view.View.layout(View.java:15678)
            at android.view.ViewGroup.layout(ViewGroup.java:5039)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15678)
            at android.view.ViewGroup.layout(ViewGroup.java:5039)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15678)
            at android.view.ViewGroup.layout(ViewGroup.java:5039)
            at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
            at android.view.View.layout(View.java:15678)
            at android.view.ViewGroup.layout(ViewGroup.java:5039)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15678)
            at android.view.ViewGroup.layout(ViewGroup.java:5039)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5293)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by Logan676** [comment]
What\`s the Android OS version have you used to run the this App? Some users who used Lollipop reported that they have the same problem.

**Comment by forouher** [comment]
Android 5.1.1 on an LG Nexus 4 (cyanogenmod 12.1)

**Comment by forouher** [comment]
Interestingly, I'm unable to reproduce this bug when installing Seadroid via the Play Store.

The bug above I observed with Seadroid git e7646b7e11 installed. But they should be nearly identical, so I'm a bit confused. Maybe I screwed something up when building the .apk locally? I'll go back and double check to be sure.

**Comment by Logan676** [comment]
@forouher thanks for your report. 
> The bug above I observed with Seadroid git e7646b7 installed. But they should be nearly identical, so I'm a bit confused.

Yes, they are identical, actually every time we are releasing a new version, we build the apk based on `master` branch.
I wonder that if you still have the bug if you check out the latest commit from `develop` branch?

**Comment by forouher** [comment]
> I wonder that if you still have the bug if you check out the latest commit from develop branch?

Yes. I can reproduce it on master and develop (976387176fe2c7a75b5746b40efdb516e86ef313).

**Comment by Logan676** [comment]
@forouher thanks for your feedback, can you append the error log?

**Comment by forouher** [comment]
```
07-07 07:11:54.621  14103-14521/com.seafile.seadroid2 D/ImageLoader﹕ Delay 500 ms before loading...  [XXXXXXXXXX&size=120_120x96]
07-07 07:11:55.159  14103-14521/com.seafile.seadroid2 D/ImageLoader﹕ Start display image task [XXXXXXXXXX&size=120_120x96]
07-07 07:11:55.159  14103-14521/com.seafile.seadroid2 D/ImageLoader﹕ Load image from disk cache [XXXXXXXXXX&size=120_120x96]
07-07 07:11:55.169  14103-14521/com.seafile.seadroid2 D/ImageLoader﹕ Cache image in memory [XXXXXXXXXX&size=120_120x96]
07-07 07:11:55.176  14103-14522/com.seafile.seadroid2 D/ImageLoader﹕ Delay 500 ms before loading...  [XXXXXXXXXX&size=120_120x96]
07-07 07:11:55.176  14103-14103/com.seafile.seadroid2 D/ImageLoader﹕ Display image in ImageAware (loaded from DISC_CACHE) [XXXXXXXXXX&size=120_120x96]
07-07 07:11:55.180  14103-14103/com.seafile.seadroid2 I/Timeline﹕ Timeline: Activity_launch_request id:com.seafile.seadroid2 time:333789521
07-07 07:11:55.215  14103-14103/com.seafile.seadroid2 D/BrowserActivity﹕ onPause
07-07 07:11:55.215  14103-14103/com.seafile.seadroid2 D/DefaultAppLock﹕ onActivityPaused
07-07 07:11:55.284  14103-14159/com.seafile.seadroid2 V/AutoUpdateManager﹕ check auto upload tasks, 0 in queue
07-07 07:11:55.286  14103-14103/com.seafile.seadroid2 D/Account﹕ XXXXXXXXXX XXXXXXXXXX null XXXXXXXXXX
07-07 07:11:55.289  14103-14103/com.seafile.seadroid2 D/DefaultAppLock﹕ onActivityResumed
07-07 07:11:55.352  14103-14103/com.seafile.seadroid2 D/AndroidRuntime﹕ Shutting down VM
07-07 07:11:55.355  14103-14103/com.seafile.seadroid2 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.seafile.seadroid2, PID: 14103
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.seafile.seadroid2.ui.adapter.GalleryAdapter.getItem(int)' on a null object reference
            at com.seafile.seadroid2.ui.activity.GalleryActivity$2.onPageScrolled(GalleryActivity.java:116)
            at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1712)
            at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1633)
            at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:581)
            at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1600)
            at android.view.View.layout(View.java:15678)
            at android.view.ViewGroup.layout(ViewGroup.java:5039)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15678)
            at android.view.ViewGroup.layout(ViewGroup.java:5039)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15678)
            at android.view.ViewGroup.layout(ViewGroup.java:5039)
            at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
            at android.view.View.layout(View.java:15678)
            at android.view.ViewGroup.layout(ViewGroup.java:5039)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15678)
            at android.view.ViewGroup.layout(ViewGroup.java:5039)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5293)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
07-07 07:11:55.709  14103-14522/com.seafile.seadroid2 D/ImageLoader﹕ ImageAware is reused for another image. Task is cancelled. [XXXXXXXXXX&size=120_120x96]
```

**Comment by forouher** [comment]
btw, this patch is a workaround for the NPE:

```
--- a/src/com/seafile/seadroid2/ui/activity/GalleryActivity.java
+++ b/src/com/seafile/seadroid2/ui/activity/GalleryActivity.java
@@ -113,11 +113,13 @@ public class GalleryActivity extends SherlockFragmentActivity {
                 // page index starting from 1 instead of 0 in user interface, so plus one here
                 mPageIndexTextView.setText(String.valueOf(position + 1));
                 mPageIndex = position;
-                String linkKey = mGalleryAdapter.getItem(position);
-                if (mThumbLinkAndSeafDirentMap.containsKey(linkKey)) {
-                    currentDirent = mThumbLinkAndSeafDirentMap.get(linkKey);
-                    mPageNameTextView.setText(currentDirent.name);
-                    fileName = currentDirent.name;
+                if (mGalleryAdapter != null) {
+                    String linkKey = mGalleryAdapter.getItem(position);
+                    if (mThumbLinkAndSeafDirentMap.containsKey(linkKey)) {
+                        currentDirent = mThumbLinkAndSeafDirentMap.get(linkKey);
+                        mPageNameTextView.setText(currentDirent.name);
+                        fileName = currentDirent.name;
+                    }
                 }
             }
 
```
