### ISSUE TITLE
Upload via Share intent

### ISSUE THREAD

**Issue by christophwolff** [haiwen/seadroid#406]
It is not possible to upload files from other Apps. i.e. from a share intent from one APP to seafile. Like Google drive. Any Chance of implementing this?

**Comment by Logan676** [comment]
You can pick files from Google Drive inside of Seafile, it has implemented a [storage access framework](https://developer.android.com/guide/topics/providers/document-provider.html) if your Android  OS is Android 4.4+.  see #59 #117 #287

Simply go to Seafile --> LIBRARY TAB --> choose a folder you where want to upload to --> SAF (with Google Drive). 
The SAF stuff looks like below.
![image](https://cloud.githubusercontent.com/assets/2975850/9003276/25d9787a-379f-11e5-9f12-1b8b932af95f.png)

**Comment by christophwolff** [comment]
Thats the thing. I often get mails with pdfs and want without going from saving to google drive, open seafile and upload the file from there. I mean the share intent is there. but when i tab it, seafile crashes.

**Comment by Logan676** [comment]
As Google service & Google drive were both blocked in my area, my Android devices doesn\`t even have those Apps installed, so I can\`t reproduce and fix the bug. Anyone from the open source community can help us?

**Comment by forouher** [comment]
I can reproduce the issue:


Steps to reproduce (using Seadroid 1.8.1):
1. Go to the "Downloads" app
2. Select some file
3. share that file with Seafile
4. seafile crashes

```
07-31 11:14:52.132  18592-18592/com.seafile.seadroid2 E/CursorWindow﹕ Failed to read row 0, column -1 from a CursorWindow which has 1 rows, 7 columns.
07-31 11:14:52.132  18592-18592/com.seafile.seadroid2 D/AndroidRuntime﹕ Shutting down VM
07-31 11:14:52.133  18592-18592/com.seafile.seadroid2 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.seafile.seadroid2, PID: 18592
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.seafile.seadroid2/com.seafile.seadroid2.ui.activity.ShareToSeafileActivity}: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2356)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
            at android.app.ActivityThread.access$900(ActivityThread.java:154)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
     Caused by: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
            at android.database.CursorWindow.nativeGetString(Native Method)
            at android.database.CursorWindow.getString(CursorWindow.java:438)
            at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
            at android.database.CursorWrapper.getString(CursorWrapper.java:114)
            at com.seafile.seadroid2.ui.activity.ShareToSeafileActivity.getSharedFilePath(ShareToSeafileActivity.java:85)
            at com.seafile.seadroid2.ui.activity.ShareToSeafileActivity.onCreate(ShareToSeafileActivity.java:57)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2309)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
            at android.app.ActivityThread.access$900(ActivityThread.java:154)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by christophwolff** [comment]
@forouher @Logan676 jep, this is exactly my issue.

**Comment by Logan676** [comment]
That's because the file from Google drive does not have a physical address in the SD card or internal memory, it is not a physical file on the device. The column [MediaStore.Images.ImageColumns.DATA](https://github.com/haiwen/seadroid/blob/master/src/com/seafile/seadroid2/ui/activity/ShareToSeafileActivity.java#L85) is used for physical files on the device, which is why the `cursor isn\`t initialized correctly before accessing data`.

The way to "grab" this image (remotely) is to open an Stream and copy the file over to a temporary folder and then proceeded with copying from the input to the output and close the streams at the end. Note that this process is a network operation, that means you should never do it from the UI thread. see [Couldn't read row 0, col -1 from Cursor Window when quering from uri in Android](http://stackoverflow.com/a/26802011/3962551)

**Comment by christophwolff** [comment]
But its die Download Folder fro what i want to share to seafile. Has nothing todo with a cloud drive.

**Comment by forouher** [comment]
@Logan I think I know what you mean. I'm on vacation at the moment, but in a week or so I'd be happy to test that idea out.

Regards
Dariush

Am 23. August 2015 12:04:18 MESZ, schrieb Logan Guo <notifications@github.com>:

**Comment by forouher** [comment]
Mught still explain the bug. The "stream api" can be used by any app, even if it has a local file.

Regards
Dariush

Am 23. August 2015 21:05:38 MESZ, schrieb Christoph Wolff <notifications@github.com>:

**Comment by Logan676** [comment]
@forouher Actually this patch was inspired by your commit 0e3ff9641cceeada24288607360d4bd0272685b1, which fixes file upload from all sources (local or remote).

**Comment by Logan676** [comment]
@christophwolff the patch #417 has passed the testing on uploading files shared from Google Drive and Downloads, we will release a new version which supports this feature soon. You can try it again then.

**Comment by christophwolff** [comment]
@Logan676 Thanks! Works like a charm!
