### ISSUE TITLE
If one file fails to upload, all subsequent ones are not even tried

### ISSUE THREAD

**Issue by tomchiverton** [haiwen/seadroid#451]
For instance, one overly large video file will prevent later small ones from even being attempted ot be uploaded.

`adb logcat CameraSyncAdapter:D *:E` shows over and over again

```
D/CameraSyncAdapter( 2819): File DSC_0562.JPG in bucket 100ANDRO already exists on the server. Skipping.
D/CameraSyncAdapter( 2819): File DSC_0563.JPG in bucket 100ANDRO already exists on the server. Skipping.
D/CameraSyncAdapter( 2819): File DSC_0564.JPG in bucket 100ANDRO already exists on the server. Skipping.
D/CameraSyncAdapter( 2819): File DSC_0565.JPG in bucket 100ANDRO already exists on the server. Skipping.
D/CameraSyncAdapter( 2819): i see 13 new videos.
D/CameraSyncAdapter( 2819): File MOV_0148.mp4 in bucket 100ANDRO already exists on the server. SkippingI/CameraSyncAdapter( 2819): sync aborted because of IO or server-side error.
I/CameraSyncAdapter( 2819): SeafException{code=2, msg=Network Error}
I/CameraSyncAdapter( 2819):     at com.seafile.seadroid2.SeafConnection.getSeafExceptionFromHttpRequestException(SeafConnection.java:1121)
I/CameraSyncAdapter( 2819):     at com.seafile.seadroid2.SeafConnection.uploadFileCommon(SeafConnection.java:683)
I/CameraSyncAdapter( 2819):     at com.seafile.seadroid2.SeafConnection.uploadFile(SeafConnection.java:564)
I/CameraSyncAdapter( 2819):     at com.seafile.seadroid2.data.DataManager.uploadFileCommon(DataManager.java:558)
I/CameraSyncAdapter( 2819):     at com.seafile.seadroid2.data.DataManager.uploadFile(DataManager.java:543)
I/CameraSyncAdapter( 2819):     at com.seafile.seadroid2.cameraupload.CameraSyncAdapter.uploadFile(CameraSyncAdapter.java:452)
I/CameraSyncAdapter( 2819):     at com.seafile.seadroid2.cameraupload.CameraSyncAdapter.iterateCursor(CameraSyncAdapter.java:419)
I/CameraSyncAdapter( 2819):     at com.seafile.seadroid2.cameraupload.CameraSyncAdapter.uploadImages(CameraSyncAdapter.java:309)
I/CameraSyncAdapter( 2819):     at com.seafile.seadroid2.cameraupload.CameraSyncAdapter.onPerformSync(CameraSyncAdapter.java:229)
I/CameraSyncAdapter( 2819):     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259.
```

The account in Settings will always say "Sync is ON" and give no indication of their being an issue.

**Comment by forouher** [comment]
Thanks! I hadn't thought of that. Will certainly address this.

(Note: This issue references PR #444, not any official Seafile release)
