### ISSUE TITLE
Seadroid 2.0.0 crashes on opening a big library

### ISSUE THREAD

**Issue by moonwalkersyrius** [haiwen/seadroid#475]
I have a library with about 20k+ files and overall size of about 4-5TiB, I can access it just fine from browser or desktop client and even through webdav (though it takes about a minute or two to load the directory listing), but if I try to access it through mobile client on Android it immediately crashes.

Server is 5.0.3 on 64-bit Debian, client is 2.0.0 on CyanogenMod 13 on Nexus 6P. Let me know if you need any additional info and what exactly you need, I'll do my best to provide it.

**Comment by Logan676** [comment]
What is the Android version of your Nexus 6P? 

>Beginning in Android 6.0 (API level 23), users grant permissions to apps while the app is running, not when they install the app. 

If it`s 6.0, you need to grant storage permission to Seafile manly, go to Settings -> Apps -> Seafile -> Permissions -> Grant Storage permission.

We will fix the bug by [Requesting Permissions at Run Time](http://developer.android.com/training/permissions/requesting.html) with next version.

**Comment by moonwalkersyrius** [comment]
Storage permission doesn't seem to be an issue, I have it. I was able to open several other folders, both new and old, as well as download individual files. The application crashes for me only under two conditions: 1) I attempt to open that 6+TiB folder with 20+k files in it and 2) I attempt to select all and download all of the pictures in my Pictures/Wallpapers folder, which contains about 190 files averaging at 2-3 MiB per file. The second issue is probably unrelated though to the big folder issue, and it's the big folder issue that's bothering me the most.

**Comment by forouher** [comment]
I have reproduced the issue with 30k empty files:

>$ for i in $(seq 1 30000); do touch $i.txt; done

[i have them on seacloud.cc. I can share the repository if someone wants to test this.]

Steps to reproduce:
1. Create loads of files in a repo dir (# files necessary might depend on memory/device. 30k did the trick on an Nexus 4)
2. browse with Seadroid into that directory (loading will take time). listing is shown correctly and cached.
3. go to parent dir.
4. revisit the dir with the 30k files
5. seadroid will load the dirent from cache. and crash.

```
02-01 23:01:53.179 27896-32262/com.seafile.seadroid2 W/CursorWindow: Window is full: requested allocation 6588895 bytes, free space 2096667 bytes, window size 2097152 bytes
02-01 23:01:53.239 27896-32262/com.seafile.seadroid2 W/CursorWindow: Window is full: requested allocation 6588895 bytes, free space 2096667 bytes, window size 2097152 bytes
02-01 23:01:53.241 27896-32262/com.seafile.seadroid2 E/CursorWindow: Failed to read row 0, column 0 from a CursorWindow which has 0 rows, 2 columns.
02-01 23:01:53.259 27896-32262/com.seafile.seadroid2 E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                       Process: com.seafile.seadroid2, PID: 27896
                                                                       java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                           at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                           at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                           at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                                           at android.database.CursorWindow.nativeGetString(Native Method)
                                                                           at android.database.CursorWindow.getString(CursorWindow.java:438)
                                                                           at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
                                                                           at com.seafile.seadroid2.data.DatabaseHelper.getCachedDirents(DatabaseHelper.java:500)
                                                                           at com.seafile.seadroid2.data.DataManager.getDirentsFromServer(DataManager.java:468)
                                                                           at com.seafile.seadroid2.ui.fragment.ReposFragment$LoadDirTask.doInBackground(ReposFragment.java:841)
                                                                           at com.seafile.seadroid2.ui.fragment.ReposFragment$LoadDirTask.doInBackground(ReposFragment.java:806)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                           at java.lang.Thread.run(Thread.java:818) 
```

The issue seems to be in loading the cached dirents from the sqlite database. The dirents of a directory are currently stored as one large json TEXT string. My guess is that this large text field exceeds the capabilities of the android sqlite implementation:

http://stackoverflow.com/questions/6938405/how-to-load-more-than-1-mb-data-from-sqlite-db-to-android-cursor

I think the proper way to solve this would be to
* redesign the DirentsCache caching SQL table so that the dirents are stored entry by entry, not as one large blob (probably best to use two tables).
* modify the ReposFragment to only display a window of entries and dynamically load more entries while scrolling (like Seahub does it on the web). My Nexus 4 is actually able to display a ListView with 30k entries (after some GC runs :-), but I'm not sure if this is a good idea in general...

**Comment by forouher** [comment]
Although that would be quite a big refactoring for a rather rare problem. And it doesn't solve the problem that in practice you can't scroll through 20k files anyway (especially on a 4" display ;).

So a simpler solution might be to simply limit the dirent cache to some reasonable size, e.g. 1000 files...

**Comment by Logan676** [comment]
What about storing identifiers in database and put the blobs as files onto the storage?
Just like the internal implementation for caching repos. See https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/data/DataManager.java#L355

Please notice that, the internal caching implementations for repos and dirents are different now, which should be refactored.

For dirents caching, simply updating the data table, change the column `content` to be `cache` and make it only save the paths for the real cached JSON files should work.

**Comment by forouher** [comment]
You're right, that would be the best solution. I'll write up a patch.

**Comment by forouher** [comment]
Can IDs of Repos (99b758e6-91ab-4265-b705-925367374cf0) and Dirents (e4fe14c8cda2206bb9606907cf4fca6b30221cf9) assumed to be **unique across servers** ?

They look to be [GUIDs](https://de.wikipedia.org/wiki/Globally_Unique_Identifier), but it is not explicitly mentioned in the API2.

**Comment by Logan676** [comment]
Yes, the id is the hash value of its content.
