### ISSUE TITLE
another crash on start after upgrade

### ISSUE THREAD

**Issue by allanman** [haiwen/seadroid#497]
```
03-10 19:36:28.960 18273 18273 D AndroidRuntime: Shutting down VM
03-10 19:36:28.961 18273 18273 E AndroidRuntime: FATAL EXCEPTION: main
03-10 19:36:28.961 18273 18273 E AndroidRuntime: Process: com.seafile.seadroid2, PID: 18273
03-10 19:36:28.961 18273 18273 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.seafile.seadroid2/com.seafile.seadroid2.ui.activity.BrowserActivity}: java.lang.NullPointerException: Attempt to get length of null array
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2462)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5514)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at com.seafile.seadroid2.data.DatabaseHelper.onUpgrade(DatabaseHelper.java:166)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at com.seafile.seadroid2.data.DatabaseHelper.getDatabaseHelper(DatabaseHelper.java:95)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at com.seafile.seadroid2.data.DataManager.<init>(DataManager.java:53)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at com.seafile.seadroid2.ui.activity.BrowserActivity.onCreate(BrowserActivity.java:241)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6271)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415)
03-10 19:36:28.961 18273 18273 E AndroidRuntime: 	... 9 more
03-10 19:36:28.962  1416  4622 D ActivityManager: New dropbox entry: com.seafile.seadroid2, data_app_crash, 7dc5ddc7-0351-4fb5-8e0e-896b42a815bc
03-10 19:36:28.964  1416  4622 W ActivityManager:   Force finishing activity com.seafile.seadroid2/.ui.activity.BrowserActivity

**Comment by allanman** [comment]
noticed the app did not have permission "Storage" allowed, that's why it crashed. 
so not critical, but should probably warn instead.

**Comment by Logan676** [comment]
Fix it at #477, so what is your Android OS version?

**Comment by allanman** [comment]
it's 6.0

**Comment by Logan676** [comment]
Then when first time you open the app, a window will pops up and asks you for external storage permissions, just simply grant that permission will solve the problem.
