### ISSUE TITLE
"Could not create repo directory" when trying to access "Whatsapp Images" backed up to Seafile on a Samsung Galaxy S4

### ISSUE THREAD

**Issue by jamietanna** [haiwen/seadroid#628]
There is a Library in Seafile, called `Photo phone`, which was backed up to previously.

When accessing the only non-empty directory in the Library, `/My Photos/WhatsApp Images` on a Samsung Galaxy S4 (client v2.1.10) the application crashes, and the logs display the below stacktrace:

```
D/AndroidRuntime(22828): Shutting down VM
E/AndroidRuntime(22828): FATAL EXCEPTION: main
E/AndroidRuntime(22828): Process: com.seafile.seadroid2, PID: 22828
E/AndroidRuntime(22828): java.lang.RuntimeException: Could not create repo directory Photo PhonePhone storage space is insufficient or too many Photo Phone directory in phone
E/AndroidRuntime(22828): 	at com.seafile.seadroid2.data.DataManager.getRepoDir(DataManager.java:247)
E/AndroidRuntime(22828): 	at com.seafile.seadroid2.data.DataManager.getLocalRepoFile(DataManager.java:265)
E/AndroidRuntime(22828): 	at com.seafile.seadroid2.ui.adapter.SeafItemAdapter.setFileView(SeafItemAdapter.java:345)
E/AndroidRuntime(22828): 	at com.seafile.seadroid2.ui.adapter.SeafItemAdapter.getDirentView(SeafItemAdapter.java:317)
E/AndroidRuntime(22828): 	at com.seafile.seadroid2.ui.adapter.SeafItemAdapter.getView(SeafItemAdapter.java:467)
E/AndroidRuntime(22828): 	at android.widget.AbsListView.obtainView(AbsListView.java:2823)
E/AndroidRuntime(22828): 	at android.widget.ListView.makeAndAddView(ListView.java:1884)
E/AndroidRuntime(22828): 	at android.widget.ListView.fillSpecific(ListView.java:1364)
E/AndroidRuntime(22828): 	at android.widget.ListView.layoutChildren(ListView.java:1671)
E/AndroidRuntime(22828): 	at android.widget.AbsListView.onLayout(AbsListView.java:2627)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:596)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
E/AndroidRuntime(22828): 	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
E/AndroidRuntime(22828): 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1192)
E/AndroidRuntime(22828): 	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
E/AndroidRuntime(22828): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
E/AndroidRuntime(22828): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
E/AndroidRuntime(22828): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
E/AndroidRuntime(22828): 	at android.view.View.layout(View.java:16711)
E/AndroidRuntime(22828): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime(22828): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2319)
E/AndroidRuntime(22828): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2032)
E/AndroidRuntime(22828): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
E/AndroidRuntime(22828): 	at andr
D/EnterpriseDeviceManagerService(  899): isManagedProfileUser(): userId = 0
D/EnterpriseDeviceManagerService(  899): is permission granted: false
V/ApplicationPolicy(  899): isApplicationStateBlocked userId 0 pkgname com.seafile.seadroid2
W/ActivityManager(  899):   Force finishing activity com.seafile.seadroid2/.ui.activity.BrowserActivity
```

However, when accessing it on a Tesco Hudl2 (client v2.1.9), the folder opens successfully.

**Comment by jamietanna** [comment]
I have just tested Tesco Hudl2 (client v2.1.10), and can confirm that the folder opens successfully, too.
