### ISSUE TITLE
2.1.12 app crash if would like to open a document

### ISSUE THREAD

**Issue by TMHBOFH** [haiwen/seadroid#656]
debug show 

_05-23 18:57:07.321 4306-4306/com.seafile.seadroid2.debug E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.seafile.seadroid2.debug, PID: 4306
android.os.FileUriExposedException: file:///storage/emulated/0/Seafile/xxxx%40xxxxx.xxx%20(xxx.xxx.xxx.xx)/Test/Ihre%20Bestellung%20-%20Druckansicht.pdf exposed beyond app through Intent.getData()
at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
at android.net.Uri.checkFileUriExposed(Uri.java:2346)
at android.content.Intent.prepareToLeaveProcess(Intent.java:8933)
at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
at android.app.Activity.startActivityForResult(Activity.java:4224)
at android.app.Activity.startActivityForResult(Activity.java:4183)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
at android.app.Activity.startActivity(Activity.java:4507)
at android.app.Activity.startActivity(Activity.java:4475)
at com.seafile.seadroid2.ui.WidgetUtils.showFile(WidgetUtils.java:147)
at com.seafile.seadroid2.ui.activity.BrowserActivity.onFileSelected(BrowserActivity.java:1539)
at com.seafile.seadroid2.ui.fragment.ReposFragment.onListItemClick(ReposFragment.java:652)
at android.support.v4.app.ListFragment$2.onItemClick(ListFragment.java:58)
at android.widget.AdapterView.performItemClick(AdapterView.java:310)
at android.widget.AbsListView.performItemClick(AbsListView.java:1155)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3120)
at android.widget.AbsListView$3.run(AbsListView.java:4035)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
--------- beginning of system_

The change on targetSdkVersion 25 could be the problem. 
Please see [link](https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed). "_If your targetSdkVersion is 24 or higher, we have to use FileProvider class to give access to the particular file or folder to make them accessible for other apps._"

If i compile with targetSdkVersion 23 this part works fine.

**Comment by xifi-kif** [comment]
same issue here: app just crashs when trying to open a file.
seafile android app version: 2.1.12
android version: 7.1.1
os: Lineage os
phone: SGS 4 mini LTE

**Comment by Flowmatix** [comment]
Experiencing exactly the same behaviour.
seafile android app version: 2.1.12
android version: 7.1.2
os: Lineage OS
phone: Oneplus One

**Comment by kwimberl** [comment]
+1
seafile android app version: 2.1.12
android version: 7.0
os: Lineage OS
phone: Nexus 6

**Comment by alansumm** [comment]
Me too.
seafile android app version: 2.1.12
android version: 7.0
os: plain Android
phone: Honor 8

Reverted to Version 2.1.11, not experiencing this bug

**Comment by andrew2005** [comment]
+1

seafile android app version: 2.1.12
android version: 7.1.2
os: Stock Android
phone: Google Pixel
