### ISSUE TITLE
had EXCEPTION on v2.2.3

### ISSUE THREAD

**Issue by wuyougan** [haiwen/seadroid#734]
one plus 3 (android 7.1)

The program crashes when I click on settings.

```
04-18 22:52:37.084  5191  5191 E AndroidRuntime: FATAL EXCEPTION: main
04-18 22:52:37.084  5191  5191 E AndroidRuntime: Process: com.seafile.seadroid2, PID: 5191
04-18 22:52:37.084  5191  5191 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.seafile.seadroid2/com.seafile.seadroid2.ui.activity.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2733)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6321)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at com.seafile.seadroid2.cameraupload.GalleryBucketUtils.getImageBuckets(GalleryBucketUtils.java:143)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at com.seafile.seadroid2.cameraupload.GalleryBucketUtils.getMediaBuckets(GalleryBucketUtils.java:45)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at com.seafile.seadroid2.ui.fragment.SettingsFragment.refreshCameraUploadView(SettingsFragment.java:627)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at com.seafile.seadroid2.ui.fragment.SettingsFragment.onViewCreated(SettingsFragment.java:401)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1322)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6777)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2696)
04-18 22:52:37.084  5191  5191 E AndroidRuntime: 	... 9 more
```

**Comment by SaudM** [comment]
You have not “Camera” dir in SD card，but  you  open “Turn on Camera Upload” int settings

**Comment by SaudM** [comment]
You have not “Camera” dir in SD card，but you  “Turn on Camera Upload” int settings
