### ISSUE TITLE
Photos synchronization no longer working

### ISSUE THREAD

**Issue by Jognu** [haiwen/seadroid#738]
Hi,
I don't know if this is due to a change on my phone (Honor 8 on Android 7 with security update from april) after an update, but I no longer can synchronize the photos.

Here is what I can see with logcat :
```
05-01 15:58:05.742: E/CameraSyncAdapter(4938): sync aborted because an unknown error
05-01 15:58:05.742: E/CameraSyncAdapter(4938): java.lang.NullPointerException: Attempt to read from field 'com.seafile.seadroid2.transfer.TaskState com.seafile.seadroid2.transfer.TransferTaskInfo.state' on a null object reference
05-01 15:58:05.742: E/CameraSyncAdapter(4938): 	at com.seafile.seadroid2.cameraupload.CameraSyncAdapter.waitForUploads(CameraSyncAdapter.java:542)
05-01 15:58:05.742: E/CameraSyncAdapter(4938): 	at com.seafile.seadroid2.cameraupload.CameraSyncAdapter.iterateCursor(CameraSyncAdapter.java:531)
05-01 15:58:05.742: E/CameraSyncAdapter(4938): 	at com.seafile.seadroid2.cameraupload.CameraSyncAdapter.uploadImages(CameraSyncAdapter.java:406)
05-01 15:58:05.742: E/CameraSyncAdapter(4938): 	at com.seafile.seadroid2.cameraupload.CameraSyncAdapter.onPerformSync(CameraSyncAdapter.java:310)
05-01 15:58:05.742: E/CameraSyncAdapter(4938): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
05-01 15:58:05.803: E/ServiceManager(429): try to find service failed, not allowed access from isolated processes.

```

**Comment by SaudM** [comment]
it work version 2.2.4

**Comment by SaudM** [comment]
int version 2.2.4  it working
