### ISSUE TITLE
Crash when opening the settings

### ISSUE THREAD

**Issue by privnote42** [haiwen/seadroid#874]
Hello,
My app always crashes when I open the settings in the App.
I looked into the debugger and there the following exception is thrown

```
W/System.err: android.database.sqlite.SQLiteException: near "GROUP": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT bucket_id, bucket_display_name, _data FROM video WHERE ((is_pending=0) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' , '1df5-191b' ))) AND ((1) GROUP BY 1,(2)) ORDER BY bucket_display_name ASC
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
W/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
W/System.err:     at com.seafile.seadroid2.cameraupload.GalleryBucketUtils.getVideoBuckets(GalleryBucketUtils.java:78)
        at com.seafile.seadroid2.cameraupload.GalleryBucketUtils.getMediaBuckets(GalleryBucketUtils.java:47)
        at com.seafile.seadroid2.ui.fragment.SettingsFragment.refreshCameraUploadView(SettingsFragment.java:628)
W/System.err:     at com.seafile.seadroid2.ui.fragment.SettingsFragment.onActivityResult(SettingsFragment.java:693)
```

**Comment by maxiaoping** [comment]
Please upgrade to the latest version

**Comment by xifi-kif** [comment]
I have same issue. Latest version here 2.2.34

**Comment by xifi-kif** [comment]
ok very wierd thing: I have two same identical devices, same os version, same seadroid version, connected to same server.
One crashes, the other doesn't.
Will dig deeper into this

**Comment by Elinvention** [comment]
I get the same stack trace as @xifi-kif on Android 11 and Seadroid 2.2.35. However I think it probably has a different cause than what @privnote42  has reported.

**Comment by DPTJKKVH** [comment]
Xiaomi Mi Mix
LineageOS 18.1
SeaFile Android 2.2.36

When opening the Settings the App crashes. This is the logcat.

```
[05-18 14:57:23.034 12466:12466 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.seafile.seadroid2, PID: 12466
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at com.seafile.seadroid2.cameraupload.GalleryBucketUtils$Bucket.hashCode(SourceFile:51)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at com.seafile.seadroid2.ui.fragment.SettingsFragment.refreshCameraUploadView(SourceFile:634)
	at com.seafile.seadroid2.ui.fragment.SettingsFragment.onViewCreated(SourceFile:406)
	at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1439)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1827)
	at android.support.v4.app.BackStackRecord.executeOps(SourceFile:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(SourceFile:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(SourceFile:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(SourceFile:2338)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(SourceFile:2245)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(SourceFile:3248)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(SourceFile:3200)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(SourceFile:195)
	at android.support.v4.app.FragmentActivity.onStart(SourceFile:597)
	at android.support.v7.app.AppCompatActivity.onStart(SourceFile:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8024)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by darlexlin** [comment]
![Screenshot_2021-05-18-21-20-09-162_com.miui.thirdappassistant.jpg](https://user-images.githubusercontent.com/6850890/118658519-0c9c5100-b81f-11eb-8dbe-a847a25485e7.jpg)

**Comment by fabian-z** [comment]
I have the same issue as @xifi-kif and @Elinvention  (same stack trace) on Android 11 with Seadroid built from master - currently identical to release 2.2.36.

The settings and sync work for me after moving a null check - if you are affected, please test my fix in #894.

**Comment by AllesWasTaken** [comment]
@fabian-z hey, can you provide the apk you built with your fix?

**Comment by fabian-z** [comment]
@AllesWasTaken Sure, you can find the APK in a ZIP archive attached to this comment. It is obviously only signed with my debug keystore, so you would need to reinstall Seadroid to test this. Also keep in mind running random apps / binaries can be a security risk, so building yourself is recommended.

[seadroid-fix-874-v1.apk.zip](https://github.com/haiwen/seadroid/files/6512278/seadroid-fix-874-v1.apk.zip)

**Comment by AllesWasTaken** [comment]
@fabian-z thank you! I'm aware of that, in using a secondary device and a seafile test server, I can confirm this fix works and I don't get crashes anymore when clicking on settings, good job!

**Comment by fabian-z** [comment]
Thanks for letting me know - glad it works for you. If possible, please comment on #894 with the Android version you used to verify the fix :smile:

**Comment by DPTJKKVH** [comment]
@fabian-z Thanks, bro! I approved your pull request after reviewing the code and testing your fix. Let's hope it gets picked up by the devs soon.

I hope SeaFile is engaging better with community contributions than some other open source cloud projects do.
