### ISSUE TITLE
Crash when opening a directory containing files (as opposed to only sub-directories)

### ISSUE THREAD

**Issue by OliverLew** [haiwen/seadroid#877]
Versions:
seafile: 2.2.32 from f-droid
android: Hydrogen OS 11.0.3.3.IN21 based on Android 11

**Comment by OliverLew** [comment]
(Possible) related log output from `adb logcat':
```
01-24 14:42:35.566  2391 10535 E AndroidRuntime: Process: com.seafile.seadroid2, PID: 2391
01-24 14:42:35.566  2391 10535 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: Caused by: java.lang.RuntimeException: Could not create repo directory LibraryPhone storage space is insufficient or too many Library directory in phone
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at com.seafile.seadroid2.data.DataManager.getRepoDir(DataManager.java:271)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at com.seafile.seadroid2.data.DataManager.getLocalRepoFile(DataManager.java:289)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at com.seafile.seadroid2.ui.fragment.ReposFragment$LoadDirTask.doInBackground(ReposFragment.java:958)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at com.seafile.seadroid2.ui.fragment.ReposFragment$LoadDirTask.doInBackground(ReposFragment.java:917)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-24 14:42:35.566  2391 10535 E AndroidRuntime: 	... 3 more
```
```
01-24 18:56:36.461  1309 28937 E ANDR-RAMBOOST_SERVER: ramboost cmd_len = 124 cmd: iop_start -1 com.seafile.seadroid2 /data/app/~~qqJg8tZrj0tWiot8apdiDA==/com.seafile.seadroid2-USU_J5jAXGn7AG-FtPTiUg== false
01-24 18:56:36.463  4453  4453 E neplus.launche: Invalid ID 0x00000176.
01-24 18:56:36.475  4453  4453 E neplus.launche: Invalid ID 0x00000176.
01-24 18:56:36.476  1309 28940 E ANDR-RAMBOOST_SERVER: ramboost cmd_len = 127 cmd: iop_start 12573 com.seafile.seadroid2 /data/app/~~qqJg8tZrj0tWiot8apdiDA==/com.seafile.seadroid2-USU_J5jAXGn7AG-FtPTiUg== false
01-24 18:56:36.485  4453  4453 E neplus.launche: Invalid ID 0x00000176.
01-24 18:56:36.487  1666  3897 E ScreenModeService: getAppToken ActivityRecord{d1d55a0 u0 com.seafile.seadroid2/.ui.activity.BrowserActivity t6749}
01-24 18:56:36.488  1666  3897 E ScreenModeService: setRefreshRate token ActivityRecord{d1d55a0 u0 com.seafile.seadroid2/.ui.activity.BrowserActivity t6749} rate 0 tmpRate 0
01-24 18:56:36.488  7469  7476 E Parcel  : Reading a NULL string not supported here.
01-24 18:56:36.488  7469  7473 E horae   : setForegroundPackage, mChargingStateMachine is null!
01-24 18:56:36.497  4453  4453 E neplus.launche: Invalid ID 0x00000176.
01-24 18:56:36.508  4453  4453 E neplus.launche: Invalid ID 0x00000176.
01-24 18:56:36.528 12573 12573 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
01-24 18:56:36.529 12573 12573 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
01-24 18:56:36.549  4845  5157 E MediaProvider: Creating a non-default top level directory or deleting an existing one is not allowed!
01-24 18:56:36.549  4845  5157 E MediaProvider: Creating a non-default top level directory or deleting an existing one is not allowed!
01-24 18:56:36.554 12573 12573 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
01-24 18:56:36.566 12573 12573 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
01-24 18:56:36.577  1666  1790 E BatteryStatsService: Unable to load Power Hal or power.stats HAL
01-24 18:56:36.585 12573 12573 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
... ...
```
```
01-24 18:56:37.157  4845  5157 E MediaProvider: Creating a non-default top level directory or deleting an existing one is not allowed!
01-24 18:56:37.158 12573 28967 E ImageLoader: /storage/emulated/0/Seafile/cache/thumbnails/428614583.tmp: open failed: ENOENT (No such file or directory)
01-24 18:56:37.158 12573 28967 E ImageLoader: java.io.FileNotFoundException: /storage/emulated/0/Seafile/cache/thumbnails/428614583.tmp: open failed: ENOENT (No such file or directory)
```
```
01-24 18:56:46.134  2547  2547 E NavigationButtonUtils: res.getInteger(resId) = 2
... ...
01-24 18:56:46.480  1309 28995 E ANDR-RAMBOOST_SERVER: ramboost cmd_len = 32 cmd: iop_record com.seafile.seadroid2
```

**Comment by OliverLew** [comment]
2.2.31 works fine, might be related to #876

**Comment by john-bill** [comment]
not shure if I had the same error, but after a clean installation of 2.2.32 on Android 11 (Havoc) Seafile didn`t request the needed permissions for full storage access (only media files access). It crashes whenever I opened a library.
Installation of 2.2.31 solved this issue, after upgrade 2.2.32 is also working.

**Comment by OliverLew** [comment]
No, upgrade from 2.2.31 to 2.2.32 did not solve my problem, and both versions requested the storage access permission.

**Comment by john-bill** [comment]
I guess Seafile cannot access the "/storage/emulated/0/Seafile" directory without the correct storage permission.
(it's my first Android 11 installation, so I stumbled about this great new Android feature multiple times...)

**Comment by sainf** [comment]
I had the same problem, and @john-bill installing .31 first saves the day... I using android 10 MIUI 12.

**Comment by freeplant** [comment]
The problem should have been solved in .33 version.

**Comment by sainf** [comment]
In my phone fixed. Tested installed .33 from scratch.

**Comment by OliverLew** [comment]
Confirmed, thanks!
