### ISSUE TITLE
自从2.2.31版本开始，进去设置立即闪退

### ISSUE THREAD

**Issue by darlexlin** [haiwen/seadroid#893]
如题，测试了好多版本，一直到推到2.2.30才能正常使用

手机型号:小米9
系统:MIUI12.0.6(Android 10)

**Comment by maxiaoping** [comment]
小米手机上的问题确实有点多，之前就有人反馈，但是我找了之前的小米手机（android 7）测了没问题，每个型号每个系统版本的小米手机问题也不一样，我再找朋友借个小米9看看能不能复现此问题

**Comment by maxiaoping** [comment]
找了同学的小米11，系统（android 11）测试了最新的版本没问题呀

**Comment by darlexlin** [comment]
那就奇怪了，我从31版本开始试了一个遍，我最开始是28版本，升级了一次最新版之后就进入设置就崩溃，一直退回到30版本才能用，日志因为我没法查看，所以也不知道怎么导致的崩溃

**Comment by Ericwyn** [comment]
小米11 青春版
2.2.36 版本复现

```
--------- beginning of crash
06-03 15:38:20.173 29798 29798 E AndroidRuntime: FATAL EXCEPTION: main
06-03 15:38:20.173 29798 29798 E AndroidRuntime: Process: com.seafile.seadroid2, PID: 29798
06-03 15:38:20.173 29798 29798 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at com.seafile.seadroid2.cameraupload.GalleryBucketUtils$Bucket.hashCode(SourceFile:51)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at java.util.HashMap.hash(HashMap.java:338)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at java.util.HashMap.put(HashMap.java:611)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at java.util.HashSet.add(HashSet.java:219)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at com.seafile.seadroid2.ui.fragment.SettingsFragment.refreshCameraUploadView(SourceFile:634)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at com.seafile.seadroid2.ui.fragment.SettingsFragment.onViewCreated(SourceFile:406)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1439)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1759)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1827)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(SourceFile:797)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(SourceFile:2596)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(SourceFile:2383)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(SourceFile:2338)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(SourceFile:2245)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(SourceFile:3248)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(SourceFile:3200)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.FragmentController.dispatchActivityCreated(SourceFile:195)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onStart(SourceFile:597)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onStart(SourceFile:177)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1434)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8180)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3539)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2127)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:233)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8061)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
06-03 15:38:20.173 29798 29798 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

**Comment by fabian-z** [comment]
From what I could gather through translations and the logcat - this issue should be overlapping with #874 and #892 and should hopefully be fixed by my PR in #894 :)

**Comment by darlexlin** [comment]
最新版问题解决了
