### ISSUE TITLE
(BUG)Problems playing video online

### ISSUE THREAD

**Issue by Oiuiuiu** [haiwen/seadroid#949]
When playing a video online in the Android client, there will be a 99% probability that the video will fail to play and crash, There is a 90% chance of flashing out of the client. I'm Android 12, and I haven't tested other phones for the time being, but I've seen this problem online.

**Comment by cakedev** [comment]
I'm using a Pixel 7 and have this issue as well.

```
01-24 20:16:34.174 W/WindowManager( 1562): Exception thrown during dispatchAppVisibility Window{c65e4e7 u0 com.seafile.seadroid2/com.seafile.seadroid2.play.PlayActivity EXITING}
01-24 20:16:34.174 W/WindowManager( 1562): android.os.DeadObjectException
01-24 20:16:34.174 W/WindowManager( 1562): 	at android.os.BinderProxy.transactNative(Native Method)
01-24 20:16:34.174 W/WindowManager( 1562): 	at android.os.BinderProxy.transact(BinderProxy.java:584)
01-24 20:16:34.174 W/WindowManager( 1562): 	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:536)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3481)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1228)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:392)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6725)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:7537)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5416)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5375)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5379)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.AppTransitionController.handleClosingApps(AppTransitionController.java:1147)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.AppTransitionController.handleAppTransitionReady(AppTransitionController.java:292)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.RootWindowContainer.checkAppTransitionReady(RootWindowContainer.java:970)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:834)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:777)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:57)
01-24 20:16:34.174 W/WindowManager( 1562): 	at android.os.Handler.handleCallback(Handler.java:942)
01-24 20:16:34.174 W/WindowManager( 1562): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-24 20:16:34.174 W/WindowManager( 1562): 	at android.os.Looper.loopOnce(Looper.java:201)
01-24 20:16:34.174 W/WindowManager( 1562): 	at android.os.Looper.loop(Looper.java:288)
01-24 20:16:34.174 W/WindowManager( 1562): 	at android.os.HandlerThread.run(HandlerThread.java:67)
01-24 20:16:34.174 W/WindowManager( 1562): 	at com.android.server.ServiceThread.run(ServiceThread.java:44)

**Comment by imeio** [comment]
build.gradle

**Comment by imeio** [comment]
build.gradle
targetSdkVersion = **29**
